### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by bam241**
small change required to find Eigen3 on windows.

this goes on top of #73

### CODE REVIEW

**Comment by gonuke** [comment]
How do we find Eigen3 for MOAB on windows?  Does MOAB have it's own FindEigen as well?

**Comment by bam241** [comment]
I stole that one from MOAB.

Maybe there is a way to get the EIGEN path form libMOAB but didn't know how to do so...

**Comment by gonuke** [comment]
> I stole that one from MOAB.
> 
> Maybe there is a way to get the EIGEN path form libMOAB but didn't know how to do so...

No - that's fine.  I just wasn't sure if MOAB had their own or not - we can include one here.

**Comment by bam241** [comment]
@pshriwise @gonuke I think this should be ready

**Comment by gonuke** [comment]
Can we setup CI for this?? (incl. Windows) I know we've discussed before.  It is hard to do tests since the output is a geometry file, but we could at least confirm that it builds and runs?

**Comment by bam241** [comment]
@gonuke do you still want CI to be part of this ?

or shall we take care of this in the thx PR ?

**Comment by gonuke** [comment]
I think for now, we can rely on the plugin CI to test this, since it's the only place we use it. Maybe at our next meeting we can discuss how to incorporate some kind of CI. For example, we could build the plugin as part of this repo's CI a a test??

**Comment by gonuke** [comment]
BTW, it should be possible to get the Eigen3 path from MOAB, but let's make an issue out of that and move this forward.

**Comment by gonuke** [comment]
Thanks for helping get us up and running on Windows @bam241

**Pull request merged**
