### PR TITLE
uwuw atom keyword

### PR DESCRIPTION
**Pull request by elliottbiondo**
Per discussion with @makeclean today, this PR modifies the -U flag to support atom and mass density specification via the `rho` and nascent `atom` keywords.

### CODE REVIEW

**Comment by gonuke** [comment]
Although there is no testing infrastructure, there are some tests/test geometries.  Can you check to see if any have atom densities, and if not, tweak/copy one to have atom densities.

I'll figure out someone else to setup proper testing here...

**Comment by elliottbiondo** [comment]
@gonuke there is only 1 file with an atom density, `INP-naaPlanes`, and it only contains one cell. Maybe I should add an inp-uwuw that has both atom and mass densities?

**Comment by elliottbiondo** [comment]
@gonuke I went ahead and added a test problem.

**Comment by gonuke** [comment]
thanks @elliottbiondo

**Pull request merged**
